use stripe::CreateCheckoutSessionShippingAddressCollectionAllowedCountries;

use crate::api::sited_io::commerce::v1::ShippingCountry;

pub const ALL_STRIPE_COUNTRIES:
    [CreateCheckoutSessionShippingAddressCollectionAllowedCountries; 236] = [
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ac,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ad,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ae,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Af,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ag,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ai,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Al,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Am,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ao,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Aq,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ar,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::At,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Au,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Aw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ax,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Az,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ba,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bb,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bd,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Be,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bh,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bi,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bj,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bo,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bq,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Br,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bs,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::By,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Bz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ca,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cd,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ch,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ci,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ck,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Co,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cy,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Cz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::De,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Dj,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Dk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Dm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Do,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Dz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ec,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ee,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Eg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Eh,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Er,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Es,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Et,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Fi,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Fj,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Fk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Fo,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Fr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ga,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gb,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gd,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ge,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gh,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gi,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gp,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gq,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gs,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Gy,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Hk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Hn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Hr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ht,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Hu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Id,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ie,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Il,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Im,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::In,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Io,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Iq,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Is,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::It,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Je,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Jm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Jo,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Jp,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ke,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Kg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Kh,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ki,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Km,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Kn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Kr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Kw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ky,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::La,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lb,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Li,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ls,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Lv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ly,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ma,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Md,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Me,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ml,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mo,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mq,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ms,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mx,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::My,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Mz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Na,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Nc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ne,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ng,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ni,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Nl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::No,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Np,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Nr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Nu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Nz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Om,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pa,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pe,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ph,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ps,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Pt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Py,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Qa,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Re,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ro,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Rs,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ru,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Rw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sa,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sb,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Se,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sh,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Si,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sj,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::So,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ss,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::St,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sx,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Sz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ta,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Td,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Th,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tj,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tl,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::To,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tr,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tv,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Tz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ua,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ug,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Us,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Uy,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Uz,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Va,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Vc,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ve,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Vg,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Vn,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Vu,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Wf,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ws,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Xk,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Ye,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Yt,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Za,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Zm,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Zw,
    CreateCheckoutSessionShippingAddressCollectionAllowedCountries::Zz,
];

pub fn to_stripe_country(
    country: &i32,
) -> CreateCheckoutSessionShippingAddressCollectionAllowedCountries {
    use stripe::CreateCheckoutSessionShippingAddressCollectionAllowedCountries::*;

    let c = ShippingCountry::try_from(*country).unwrap();
    match c {
        ShippingCountry::Unspecified => {
            unreachable!()
        }
        ShippingCountry::Ac => Ac,
        ShippingCountry::Ad => Ad,
        ShippingCountry::Ae => Ae,
        ShippingCountry::Af => Af,
        ShippingCountry::Ag => Ag,
        ShippingCountry::Ai => Ai,
        ShippingCountry::Al => Al,
        ShippingCountry::Am => Am,
        ShippingCountry::Ao => Ao,
        ShippingCountry::Aq => Aq,
        ShippingCountry::Ar => Ar,
        ShippingCountry::At => At,
        ShippingCountry::Au => Au,
        ShippingCountry::Aw => Aw,
        ShippingCountry::Ax => Ax,
        ShippingCountry::Az => Az,
        ShippingCountry::Ba => Ba,
        ShippingCountry::Bb => Bb,
        ShippingCountry::Bd => Bd,
        ShippingCountry::Be => Be,
        ShippingCountry::Bf => Bf,
        ShippingCountry::Bg => Bg,
        ShippingCountry::Bh => Bh,
        ShippingCountry::Bi => Bi,
        ShippingCountry::Bj => Bj,
        ShippingCountry::Bl => Bl,
        ShippingCountry::Bm => Bm,
        ShippingCountry::Bn => Bn,
        ShippingCountry::Bo => Bo,
        ShippingCountry::Bq => Bq,
        ShippingCountry::Br => Br,
        ShippingCountry::Bs => Bs,
        ShippingCountry::Bt => Bt,
        ShippingCountry::Bv => Bv,
        ShippingCountry::Bw => Bw,
        ShippingCountry::By => By,
        ShippingCountry::Bz => Bz,
        ShippingCountry::Ca => Ca,
        ShippingCountry::Cd => Cd,
        ShippingCountry::Cf => Cf,
        ShippingCountry::Cg => Cg,
        ShippingCountry::Ch => Ch,
        ShippingCountry::Ci => Ci,
        ShippingCountry::Ck => Ck,
        ShippingCountry::Cl => Cl,
        ShippingCountry::Cm => Cm,
        ShippingCountry::Cn => Cn,
        ShippingCountry::Co => Co,
        ShippingCountry::Cr => Cr,
        ShippingCountry::Cv => Cv,
        ShippingCountry::Cw => Cw,
        ShippingCountry::Cy => Cy,
        ShippingCountry::Cz => Cz,
        ShippingCountry::De => De,
        ShippingCountry::Dj => Dj,
        ShippingCountry::Dk => Dk,
        ShippingCountry::Dm => Dm,
        ShippingCountry::Do => Do,
        ShippingCountry::Dz => Dz,
        ShippingCountry::Ec => Ec,
        ShippingCountry::Ee => Ee,
        ShippingCountry::Eg => Eg,
        ShippingCountry::Eh => Eh,
        ShippingCountry::Er => Er,
        ShippingCountry::Es => Es,
        ShippingCountry::Et => Et,
        ShippingCountry::Fi => Fi,
        ShippingCountry::Fj => Fj,
        ShippingCountry::Fk => Fk,
        ShippingCountry::Fo => Fo,
        ShippingCountry::Fr => Fr,
        ShippingCountry::Ga => Ga,
        ShippingCountry::Gb => Gb,
        ShippingCountry::Gd => Gd,
        ShippingCountry::Ge => Ge,
        ShippingCountry::Gf => Gf,
        ShippingCountry::Gg => Gg,
        ShippingCountry::Gh => Gh,
        ShippingCountry::Gi => Gi,
        ShippingCountry::Gl => Gl,
        ShippingCountry::Gm => Gm,
        ShippingCountry::Gn => Gn,
        ShippingCountry::Gp => Gp,
        ShippingCountry::Gq => Gq,
        ShippingCountry::Gr => Gr,
        ShippingCountry::Gs => Gs,
        ShippingCountry::Gt => Gt,
        ShippingCountry::Gu => Gu,
        ShippingCountry::Gw => Gw,
        ShippingCountry::Gy => Gy,
        ShippingCountry::Hk => Hk,
        ShippingCountry::Hn => Hn,
        ShippingCountry::Hr => Hr,
        ShippingCountry::Ht => Ht,
        ShippingCountry::Hu => Hu,
        ShippingCountry::Id => Id,
        ShippingCountry::Ie => Ie,
        ShippingCountry::Il => Il,
        ShippingCountry::Im => Im,
        ShippingCountry::In => In,
        ShippingCountry::Io => Io,
        ShippingCountry::Iq => Iq,
        ShippingCountry::Is => Is,
        ShippingCountry::It => It,
        ShippingCountry::Je => Je,
        ShippingCountry::Jm => Jm,
        ShippingCountry::Jo => Jo,
        ShippingCountry::Jp => Jp,
        ShippingCountry::Ke => Ke,
        ShippingCountry::Kg => Kg,
        ShippingCountry::Kh => Kh,
        ShippingCountry::Ki => Ki,
        ShippingCountry::Km => Km,
        ShippingCountry::Kn => Kn,
        ShippingCountry::Kr => Kr,
        ShippingCountry::Kw => Kw,
        ShippingCountry::Ky => Ky,
        ShippingCountry::La => La,
        ShippingCountry::Lb => Lb,
        ShippingCountry::Lc => Lc,
        ShippingCountry::Li => Li,
        ShippingCountry::Lk => Lk,
        ShippingCountry::Lr => Lr,
        ShippingCountry::Ls => Ls,
        ShippingCountry::Lt => Lt,
        ShippingCountry::Lu => Lu,
        ShippingCountry::Lv => Lv,
        ShippingCountry::Ly => Ly,
        ShippingCountry::Ma => Ma,
        ShippingCountry::Mc => Mc,
        ShippingCountry::Md => Md,
        ShippingCountry::Me => Me,
        ShippingCountry::Mf => Mf,
        ShippingCountry::Mg => Mg,
        ShippingCountry::Mk => Mk,
        ShippingCountry::Ml => Ml,
        ShippingCountry::Mm => Mm,
        ShippingCountry::Mn => Mn,
        ShippingCountry::Mo => Mo,
        ShippingCountry::Mq => Mq,
        ShippingCountry::Mr => Mr,
        ShippingCountry::Ms => Ms,
        ShippingCountry::Mt => Mt,
        ShippingCountry::Mu => Mu,
        ShippingCountry::Mv => Mv,
        ShippingCountry::Mw => Mw,
        ShippingCountry::Mx => Mx,
        ShippingCountry::My => My,
        ShippingCountry::Mz => Mz,
        ShippingCountry::Na => Na,
        ShippingCountry::Nc => Nc,
        ShippingCountry::Ne => Ne,
        ShippingCountry::Ng => Ng,
        ShippingCountry::Ni => Ni,
        ShippingCountry::Nl => Nl,
        ShippingCountry::No => No,
        ShippingCountry::Np => Np,
        ShippingCountry::Nr => Nr,
        ShippingCountry::Nu => Nu,
        ShippingCountry::Nz => Nz,
        ShippingCountry::Om => Om,
        ShippingCountry::Pa => Pa,
        ShippingCountry::Pe => Pe,
        ShippingCountry::Pf => Pf,
        ShippingCountry::Pg => Pg,
        ShippingCountry::Ph => Ph,
        ShippingCountry::Pk => Pk,
        ShippingCountry::Pl => Pl,
        ShippingCountry::Pm => Pm,
        ShippingCountry::Pn => Pn,
        ShippingCountry::Pr => Pr,
        ShippingCountry::Ps => Ps,
        ShippingCountry::Pt => Pt,
        ShippingCountry::Py => Py,
        ShippingCountry::Qa => Qa,
        ShippingCountry::Re => Re,
        ShippingCountry::Ro => Ro,
        ShippingCountry::Rs => Rs,
        ShippingCountry::Ru => Ru,
        ShippingCountry::Rw => Rw,
        ShippingCountry::Sa => Sa,
        ShippingCountry::Sb => Sb,
        ShippingCountry::Sc => Sc,
        ShippingCountry::Se => Se,
        ShippingCountry::Sg => Sg,
        ShippingCountry::Sh => Sh,
        ShippingCountry::Si => Si,
        ShippingCountry::Sj => Sj,
        ShippingCountry::Sk => Sk,
        ShippingCountry::Sl => Sl,
        ShippingCountry::Sm => Sm,
        ShippingCountry::Sn => Sn,
        ShippingCountry::So => So,
        ShippingCountry::Sr => Sr,
        ShippingCountry::Ss => Ss,
        ShippingCountry::St => St,
        ShippingCountry::Sv => Sv,
        ShippingCountry::Sx => Sx,
        ShippingCountry::Sz => Sz,
        ShippingCountry::Ta => Ta,
        ShippingCountry::Tc => Tc,
        ShippingCountry::Td => Td,
        ShippingCountry::Tf => Tf,
        ShippingCountry::Tg => Tg,
        ShippingCountry::Th => Th,
        ShippingCountry::Tj => Tj,
        ShippingCountry::Tk => Tk,
        ShippingCountry::Tl => Tl,
        ShippingCountry::Tm => Tm,
        ShippingCountry::Tn => Tn,
        ShippingCountry::To => To,
        ShippingCountry::Tr => Tr,
        ShippingCountry::Tt => Tt,
        ShippingCountry::Tv => Tv,
        ShippingCountry::Tw => Tw,
        ShippingCountry::Tz => Tz,
        ShippingCountry::Ua => Ua,
        ShippingCountry::Ug => Ug,
        ShippingCountry::Us => Us,
        ShippingCountry::Uy => Uy,
        ShippingCountry::Uz => Uz,
        ShippingCountry::Va => Va,
        ShippingCountry::Vc => Vc,
        ShippingCountry::Ve => Ve,
        ShippingCountry::Vg => Vg,
        ShippingCountry::Vn => Vn,
        ShippingCountry::Vu => Vu,
        ShippingCountry::Wf => Wf,
        ShippingCountry::Ws => Ws,
        ShippingCountry::Xk => Xk,
        ShippingCountry::Ye => Ye,
        ShippingCountry::Yt => Yt,
        ShippingCountry::Za => Za,
        ShippingCountry::Zm => Zm,
        ShippingCountry::Zw => Zw,
        ShippingCountry::Zz => Zz,
    }
}
